import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getLocalDateString } from '@/lib/date';
import { getSession } from '@/lib/auth';
import { canAccessReports } from '@/lib/roles';
import { getStartOfDay, getEndOfDay } from '@/lib/attendance';
import nodemailer from 'nodemailer';

type ReportLog = {
  employee: { name: string; employee_id: string };
  project?: { name: string; code: string } | null;
  task: string | null;
  status: string | null;
  description: string | null;
  work_date?: string;
};

function generateReportHTML(date: string, logs: ReportLog[]) {
  const grouped: Record<string, typeof logs> = {};
  for (const log of logs) {
    const name = log.employee?.name || 'Unknown';
    if (!grouped[name]) grouped[name] = [];
    grouped[name].push(log);
  }

  let rows = '';
  for (const [name, tasks] of Object.entries(grouped)) {
    for (let i = 0; i < tasks.length; i++) {
      const t = tasks[i];
      const statusColor = t.status === 'completed' ? '#10b981' : '#f59e0b';
      const statusLabel = t.status === 'completed' ? 'Completed' : 'In Progress';
      rows += `<tr style="border-bottom:1px solid #e5e7eb;">
        ${i === 0 ? `<td rowspan="${tasks.length}" style="padding:12px 16px;font-weight:600;vertical-align:top;border-right:1px solid #e5e7eb;">${name}<br/><span style="font-weight:400;color:#6b7280;font-size:12px;">${t.employee.employee_id}</span></td>` : ''}
        <td style="padding:12px 16px;">${t.task}${t.project ? `<div style="color:#2563eb;font-size:12px;margin-top:4px;">${t.project.name}</div>` : ''}</td>
        <td style="padding:12px 16px;color:#6b7280;font-size:13px;">${t.description || '—'}</td>
        <td style="padding:12px 16px;text-align:center;"><span style="background:${statusColor}15;color:${statusColor};padding:4px 12px;border-radius:20px;font-size:12px;font-weight:600;">${statusLabel}</span></td>
      </tr>`;
    }
  }

  const completedCount = logs.filter(l => l.status === 'completed').length;
  const inProgressCount = logs.length - completedCount;

  return `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;font-family:'Segoe UI',Arial,sans-serif;background:#f3f4f6;">
    <div style="max-width:800px;margin:0 auto;padding:32px 16px;">
      <div style="background:linear-gradient(135deg,#4f46e5,#7c3aed);border-radius:16px 16px 0 0;padding:32px;color:white;">
        <h1 style="margin:0 0 4px 0;font-size:24px;">GIS Team — Daily Work Report</h1>
        <p style="margin:0;opacity:0.85;font-size:14px;">Report Date: ${new Date(date).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', timeZone: 'Asia/Kolkata' })}</p>
      </div>
      <div style="background:white;padding:24px;border-radius:0 0 16px 16px;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
        <div style="display:flex;gap:16px;margin-bottom:24px;">
          <div style="flex:1;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;text-align:center;">
            <div style="font-size:28px;font-weight:700;color:#16a34a;">${completedCount}</div><div style="font-size:12px;color:#4ade80;font-weight:600;">COMPLETED</div>
          </div>
          <div style="flex:1;background:#fffbeb;border:1px solid #fde68a;border-radius:12px;padding:16px;text-align:center;">
            <div style="font-size:28px;font-weight:700;color:#d97706;">${inProgressCount}</div><div style="font-size:12px;color:#fbbf24;font-weight:600;">IN PROGRESS</div>
          </div>
          <div style="flex:1;background:#eff6ff;border:1px solid #bfdbfe;border-radius:12px;padding:16px;text-align:center;">
            <div style="font-size:28px;font-weight:700;color:#2563eb;">${Object.keys(grouped).length}</div><div style="font-size:12px;color:#60a5fa;font-weight:600;">TEAM MEMBERS</div>
          </div>
        </div>
        <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;">
          <thead><tr style="background:#f9fafb;">
            <th style="padding:12px 16px;text-align:left;font-size:12px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb;">Employee</th>
            <th style="padding:12px 16px;text-align:left;font-size:12px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb;">Task</th>
            <th style="padding:12px 16px;text-align:left;font-size:12px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb;">Description</th>
            <th style="padding:12px 16px;text-align:center;font-size:12px;text-transform:uppercase;color:#6b7280;border-bottom:2px solid #e5e7eb;">Status</th>
          </tr></thead>
          <tbody>${rows || '<tr><td colspan="4" style="padding:24px;text-align:center;color:#9ca3af;">No work logs for this date</td></tr>'}</tbody>
        </table>
        <p style="margin-top:24px;font-size:12px;color:#9ca3af;text-align:center;">Generated by GIS Team EMS • ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</p>
      </div>
    </div>
  </body></html>`;
}

export async function POST(request: NextRequest) {
  try {
    const session = await getSession();
    if (!session || !canAccessReports(session.role)) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { date, startDate, endDate, email, action } = await request.json();
    
    // Support both single date (legacy) and date range
    const today = getLocalDateString();
    const start = startDate || date || today;
    const end = endDate || start;

    const dateStart = getStartOfDay(start);
    const dateEnd = getEndOfDay(end);

    const logs = await prisma.work_status.findMany({
      where: { 
        work_date: { 
          gte: dateStart, 
          lte: dateEnd 
        } 
      },
      include: {
        employee: { select: { name: true, employee_id: true } },
        project: { select: { name: true, code: true } },
      },
      orderBy: { work_date: 'asc' },
    });

    const reportLogs: ReportLog[] = logs
      .filter((log): log is typeof log & { employee: { name: string; employee_id: string } } => Boolean(log.employee))
      .map((log) => ({
        employee: log.employee,
        project: log.project,
        task: log.task,
        status: log.status,
        description: log.description,
        work_date: log.work_date ? getLocalDateString(new Date(log.work_date)) : getLocalDateString(),
      }));

    const html = generateReportHTML(start === end ? start : `${start} to ${end}`, reportLogs);

    if (action === 'preview') {
      return NextResponse.json({ html, logs: reportLogs, logsCount: logs.length });
    }

    // Send email logic...
    const teamLeadRecipients = await prisma.employees.findMany({
      where: {
        role: 'teamlead',
        email: {
          not: null,
        },
      },
      select: {
        email: true,
      },
    });

    const fallbackRecipients = teamLeadRecipients
      .map((employee) => employee.email)
      .filter((value): value is string => Boolean(value));

    const emailTo = email || process.env.REPORT_EMAIL_TO || fallbackRecipients.join(', ');
    if (!emailTo) {
      return NextResponse.json(
        { error: 'No recipient email provided. Add a team lead email or set REPORT_EMAIL_TO.' },
        { status: 400 }
      );
    }

    const smtpHost = process.env.SMTP_HOST;
    if (!smtpHost) {
      return NextResponse.json({ error: 'SMTP not configured. Set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS in .env' }, { status: 500 });
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: Number.parseInt(process.env.SMTP_PORT || '587'),
      secure: false,
      auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
    });

    const dateLabel = start === end 
      ? new Date(start).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
      : `${new Date(start).toLocaleDateString('en-IN')} to ${new Date(end).toLocaleDateString('en-IN')}`;

    await transporter.sendMail({
      from: process.env.SMTP_USER || 'ems@gisteam.local',
      to: emailTo,
      subject: `GIS Team Report — ${dateLabel}`,
      html,
    });

    return NextResponse.json({ success: true, message: `Report sent to ${emailTo}` });
  } catch (error) {
    console.error('Report error:', error);
    return NextResponse.json({ error: 'Failed to generate report' }, { status: 500 });
  }
}
